version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:3.4.1
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - code-with-yu

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres
  networks:
    - code-with-yu

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432" 
    networks:
      - code-with-yu

  webserver:
    <<: *airflow-common
    command: bash -c "exec airflow webserver"
    ports:
      - "8080:8080"
    volumes:
    - .:/opt/airflow 
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    # ✅ 首次/幂等初始化用 db init；创建用户失败也不阻塞（|| true）
    command: bash -c "airflow db init && \
                      airflow users create --username admin --firstname Zhen --lastname Xin \
                        --role Admin --email airscholar@gmail.com --password admin || true && \
                      exec airflow scheduler"
    volumes:
    - .:/opt/airflow

  pgadmin:
    image: dpage/pgadmin4:7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   
      PGADMIN_DEFAULT_PASSWORD: admin          
    ports:
      - "5050:80"                              
    depends_on:
      - postgres
    networks:
      - code-with-yu
    volumes:
      - pgadmin_data:/var/lib/pgadmin         

networks:
  code-with-yu:

volumes:
  pgadmin_data: